// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mapos_dotnet.Data;

#nullable disable

namespace mapos_dotnet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260501100000_AddOperadorCaixa")]
    partial class AddOperadorCaixa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("mapos_dotnet.Models.Anexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeArquivo")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("arquivo");

                    b.Property<int>("OsId")
                        .HasColumnType("integer")
                        .HasColumnName("os_id");

                    b.Property<string>("Path")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("path");

                    b.Property<string>("Thumb")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("thumb");

                    b.Property<string>("Url")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("OsId");

                    b.ToTable("anexos", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.AnotacaoOs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Anotacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("anotacao");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<int>("OsId")
                        .HasColumnType("integer")
                        .HasColumnName("os_id");

                    b.HasKey("Id");

                    b.HasIndex("OsId");

                    b.ToTable("anotacoes_os", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Cadastro")
                        .HasColumnType("date")
                        .HasColumnName("cadastro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("categoria");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AsaasId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("asaas_id");

                    b.Property<string>("Bairro")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("bairro");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular");

                    b.Property<string>("Cep")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("complemento");

                    b.Property<string>("Contato")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("contato");

                    b.Property<DateOnly?>("DataCadastro")
                        .HasColumnType("date")
                        .HasColumnName("data_cadastro");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<bool>("Fornecedor")
                        .HasColumnType("boolean")
                        .HasColumnName("fornecedor");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_cliente");

                    b.Property<string>("Numero")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("numero");

                    b.Property<bool>("PessoaFisica")
                        .HasColumnType("boolean")
                        .HasColumnName("pessoa_fisica");

                    b.Property<string>("Rua")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("rua");

                    b.Property<string>("Senha")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("senha");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sexo");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Cobranca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("barcode");

                    b.Property<string>("ChargeId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("charge_id");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateOnly?>("ConditionalDiscountDate")
                        .HasColumnType("date")
                        .HasColumnName("conditional_discount_date");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CustomId")
                        .HasColumnType("integer")
                        .HasColumnName("custom_id");

                    b.Property<DateOnly>("ExpireAt")
                        .HasColumnType("date")
                        .HasColumnName("expire_at");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("link");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("message");

                    b.Property<int?>("OsId")
                        .HasColumnType("integer")
                        .HasColumnName("os_id");

                    b.Property<string>("Payment")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payment");

                    b.Property<string>("PaymentGateway")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("payment_gateway");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("payment_url");

                    b.Property<string>("Pdf")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pdf");

                    b.Property<string>("RequestDeliveryAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_delivery_address");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("status");

                    b.Property<string>("Total")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("total");

                    b.Property<int?>("VendaId")
                        .HasColumnType("integer")
                        .HasColumnName("venda_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("OsId");

                    b.HasIndex("VendaId");

                    b.ToTable("cobrancas", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("config");

                    b.Property<string>("Valor")
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("Config")
                        .IsUnique();

                    b.ToTable("configuracoes", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Banco")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("banco");

                    b.Property<DateOnly?>("Cadastro")
                        .HasColumnType("date")
                        .HasColumnName("cadastro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("conta");

                    b.Property<string>("NumeroAgencia")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("numero");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("saldo");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("contas", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Cadastro")
                        .HasColumnType("date")
                        .HasColumnName("cadastro");

                    b.Property<string>("Categoria")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("File")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("file");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("documento");

                    b.Property<string>("Path")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("path");

                    b.Property<string>("Tamanho")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("tamanho");

                    b.Property<string>("Tipo")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("tipo");

                    b.Property<string>("Url")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("documentos", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.EmailQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bcc")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bcc");

                    b.Property<string>("Cc")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cc");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Headers")
                        .HasColumnType("text")
                        .HasColumnName("headers");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("to_address");

                    b.HasKey("Id");

                    b.ToTable("email_queue", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Emitente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("cidade");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Ie")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ie");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("rua");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("Uf")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("uf");

                    b.Property<string>("UrlLogo")
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)")
                        .HasColumnName("url_logo");

                    b.HasKey("Id");

                    b.ToTable("emitente", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Cor")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("cor");

                    b.Property<DateOnly?>("DataFabricacao")
                        .HasColumnType("date")
                        .HasColumnName("data_fabricacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("descricao");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("integer")
                        .HasColumnName("marca_id");

                    b.Property<string>("Modelo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("modelo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("equipamento");

                    b.Property<string>("NumSerie")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("num_serie");

                    b.Property<string>("Potencia")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("potencia");

                    b.Property<string>("Tensao")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("tensao");

                    b.Property<string>("Voltagem")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("voltagem");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MarcaId");

                    b.ToTable("equipamentos", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.EquipamentoOs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DefeitoDeclarado")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("defeito_declarado");

                    b.Property<string>("DefeitoEncontrado")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("defeito_encontrado");

                    b.Property<int>("EquipamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("equipamento_id");

                    b.Property<int>("OsId")
                        .HasColumnType("integer")
                        .HasColumnName("os_id");

                    b.Property<string>("Solucao")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("solucao");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.HasIndex("OsId");

                    b.ToTable("equipamentos_os", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Garantia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DataGarantia")
                        .HasColumnType("date")
                        .HasColumnName("data_garantia");

                    b.Property<string>("RefGarantia")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("ref_garantia");

                    b.Property<string>("TextoGarantia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto_garantia");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("garantias", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sub_total");

                    b.Property<int>("VendaId")
                        .HasColumnType("integer")
                        .HasColumnName("venda_id");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("itens_de_vendas", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Anexo")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("anexo");

                    b.Property<bool>("Baixado")
                        .HasColumnType("boolean")
                        .HasColumnName("baixado");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<string>("ClienteFornecedor")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cliente_fornecedor");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<int?>("ContaId")
                        .HasColumnType("integer")
                        .HasColumnName("conta_id");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("data_pagamento");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("desconto");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<string>("FormaPgto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("forma_pgto");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("tipo");

                    b.Property<string>("TipoDesconto")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("tipo_desconto");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_desconto");

                    b.Property<int?>("VendaId")
                        .HasColumnType("integer")
                        .HasColumnName("venda_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ContaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VendaId");

                    b.ToTable("lancamentos", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip");

                    b.Property<string>("Tarefa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tarefa");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("usuario");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Cadastro")
                        .HasColumnType("date")
                        .HasColumnName("cadastro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marca");

                    b.Property<bool>("Situacao")
                        .HasColumnType("boolean")
                        .HasColumnName("situacao");

                    b.HasKey("Id");

                    b.ToTable("marcas", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Os", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateOnly?>("DataFinal")
                        .HasColumnType("date")
                        .HasColumnName("data_final");

                    b.Property<DateOnly?>("DataInicial")
                        .HasColumnType("date")
                        .HasColumnName("data_inicial");

                    b.Property<string>("Defeito")
                        .HasColumnType("text")
                        .HasColumnName("defeito");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("desconto");

                    b.Property<string>("DescricaoProduto")
                        .HasColumnType("text")
                        .HasColumnName("descricao_produto");

                    b.Property<bool>("Faturado")
                        .HasColumnType("boolean")
                        .HasColumnName("faturado");

                    b.Property<string>("Garantia")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("garantia");

                    b.Property<int?>("GarantiaId")
                        .HasColumnType("integer")
                        .HasColumnName("garantia_id");

                    b.Property<int?>("LancamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("lancamento_id");

                    b.Property<string>("LaudoTecnico")
                        .HasColumnType("text")
                        .HasColumnName("laudo_tecnico");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("status");

                    b.Property<string>("TipoDesconto")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("tipo_desconto");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_desconto");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("GarantiaId");

                    b.HasIndex("LancamentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("os", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<string>("Permissoes")
                        .HasColumnType("text")
                        .HasColumnName("permissoes");

                    b.Property<bool>("Situacao")
                        .HasColumnType("boolean")
                        .HasColumnName("situacao");

                    b.HasKey("Id");

                    b.ToTable("permissoes", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<string>("CodDeBarra")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("cod_de_barra");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Entrada")
                        .HasColumnType("boolean")
                        .HasColumnName("entrada");

                    b.Property<int>("Estoque")
                        .HasColumnType("integer")
                        .HasColumnName("estoque");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("estoque_minimo");

                    b.Property<decimal>("PrecoCompra")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_compra");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_venda");

                    b.Property<bool>("Saida")
                        .HasColumnType("boolean")
                        .HasColumnName("saida");

                    b.Property<string>("Unidade")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unidade");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("produtos", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.ProdutoOs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("descricao");

                    b.Property<int>("OsId")
                        .HasColumnType("integer")
                        .HasColumnName("os_id");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sub_total");

                    b.HasKey("Id");

                    b.HasIndex("OsId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("produtos_os", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.ResetSenha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_expiracao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.Property<bool>("TokenUtilizado")
                        .HasColumnType("boolean")
                        .HasColumnName("token_utilizado");

                    b.HasKey("Id");

                    b.ToTable("resets_de_senha", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.HasKey("Id");

                    b.ToTable("servicos", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.ServicoOs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OsId")
                        .HasColumnType("integer")
                        .HasColumnName("os_id");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco");

                    b.Property<double>("Quantidade")
                        .HasColumnType("double precision")
                        .HasColumnName("quantidade");

                    b.Property<string>("Servico")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("servico");

                    b.Property<int>("ServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("servico_id");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sub_total");

                    b.HasKey("Id");

                    b.HasIndex("OsId");

                    b.HasIndex("ServicoId");

                    b.ToTable("servicos_os", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.SessaoCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AbertoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aberto_em");

                    b.Property<decimal?>("Diferenca")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("diferenca");

                    b.Property<DateTime?>("FechadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechado_em");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<int>("OperadorId")
                        .HasColumnType("integer")
                        .HasColumnName("operador_id");

                    b.Property<decimal>("SaldoEsperado")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("saldo_esperado");

                    b.Property<decimal?>("SaldoInformado")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("saldo_informado");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("saldo_inicial");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId");

                    b.ToTable("sessoes_caixa", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("bairro");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("celular");

                    b.Property<string>("Cep")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("cidade");

                    b.Property<string>("Cpf")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cpf");

                    b.Property<DateOnly?>("DataCadastro")
                        .HasColumnType("date")
                        .HasColumnName("data_cadastro");

                    b.Property<DateOnly?>("DataExpiracao")
                        .HasColumnType("date")
                        .HasColumnName("data_expiracao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<bool>("FiscalPdv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("fiscal_pdv");

                    b.Property<string>("FiscalPdvCodigo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("fiscal_pdv_codigo");

                    b.Property<string>("FiscalPdvPin")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fiscal_pdv_pin");

                    b.Property<bool>("OperadorCaixa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("operador_caixa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("numero");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("integer")
                        .HasColumnName("permissao_id");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rg");

                    b.Property<string>("Rua")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("rua");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("senha");

                    b.Property<bool>("Situacao")
                        .HasColumnType("boolean")
                        .HasColumnName("situacao");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("UrlImageUser")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("url_image_user");

                    b.HasKey("Id");

                    b.HasIndex("PermissaoId");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateOnly>("DataVenda")
                        .HasColumnType("date")
                        .HasColumnName("data_venda");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("desconto");

                    b.Property<bool>("Faturado")
                        .HasColumnType("boolean")
                        .HasColumnName("faturado");

                    b.Property<string>("FormaPagamento")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("forma_pagamento");

                    b.Property<int?>("GarantiaId")
                        .HasColumnType("integer")
                        .HasColumnName("garantia_id");

                    b.Property<int?>("LancamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("lancamento_id");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("ObservacoesCliente")
                        .HasColumnType("text")
                        .HasColumnName("observacoes_cliente");

                    b.Property<int?>("SessaoCaixaId")
                        .HasColumnType("integer")
                        .HasColumnName("sessao_caixa_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("status");

                    b.Property<string>("TipoDesconto")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("tipo_desconto");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_desconto");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LancamentoId");

                    b.HasIndex("SessaoCaixaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("vendas", (string)null);
                });

            modelBuilder.Entity("mapos_dotnet.Models.Anexo", b =>
                {
                    b.HasOne("mapos_dotnet.Models.Os", "Os")
                        .WithMany("Anexos")
                        .HasForeignKey("OsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Os");
                });

            modelBuilder.Entity("mapos_dotnet.Models.AnotacaoOs", b =>
                {
                    b.HasOne("mapos_dotnet.Models.Os", "Os")
                        .WithMany("Anotacoes")
                        .HasForeignKey("OsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Os");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Cobranca", b =>
                {
                    b.HasOne("mapos_dotnet.Models.Cliente", "Cliente")
                        .WithMany("Cobrancas")
                        .HasForeignKey("ClienteId");

                    b.HasOne("mapos_dotnet.Models.Os", "Os")
                        .WithMany("Cobrancas")
                        .HasForeignKey("OsId");

                    b.HasOne("mapos_dotnet.Models.Venda", "Venda")
                        .WithMany("Cobrancas")
                        .HasForeignKey("VendaId");

                    b.Navigation("Cliente");

                    b.Navigation("Os");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Equipamento", b =>
                {
                    b.HasOne("mapos_dotnet.Models.Cliente", "Cliente")
                        .WithMany("Equipamentos")
                        .HasForeignKey("ClienteId");

                    b.HasOne("mapos_dotnet.Models.Marca", "Marca")
                        .WithMany("Equipamentos")
                        .HasForeignKey("MarcaId");

                    b.Navigation("Cliente");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("mapos_dotnet.Models.EquipamentoOs", b =>
                {
                    b.HasOne("mapos_dotnet.Models.Equipamento", "Equipamento")
                        .WithMany("EquipamentosOs")
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mapos_dotnet.Models.Os", "Os")
                        .WithMany("EquipamentosOs")
                        .HasForeignKey("OsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamento");

                    b.Navigation("Os");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Garantia", b =>
                {
                    b.HasOne("mapos_dotnet.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("mapos_dotnet.Models.ItemVenda", b =>
                {
                    b.HasOne("mapos_dotnet.Models.Produto", "Produto")
                        .WithMany("ItensVenda")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mapos_dotnet.Models.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Lancamento", b =>
                {
                    b.HasOne("mapos_dotnet.Models.Categoria", "Categoria")
                        .WithMany("Lancamentos")
                        .HasForeignKey("CategoriaId");

                    b.HasOne("mapos_dotnet.Models.Cliente", "Cliente")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ClienteId");

                    b.HasOne("mapos_dotnet.Models.Conta", "Conta")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContaId");

                    b.HasOne("mapos_dotnet.Models.Usuario", "Usuario")
                        .WithMany("Lancamentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mapos_dotnet.Models.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId");

                    b.Navigation("Categoria");

                    b.Navigation("Cliente");

                    b.Navigation("Conta");

                    b.Navigation("Usuario");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Log", b =>
                {
                    b.HasOne("mapos_dotnet.Models.Usuario", "UsuarioNav")
                        .WithMany("Logs")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("UsuarioNav");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Os", b =>
                {
                    b.HasOne("mapos_dotnet.Models.Cliente", "Cliente")
                        .WithMany("OsList")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mapos_dotnet.Models.Garantia", "GarantiaTermo")
                        .WithMany("OsList")
                        .HasForeignKey("GarantiaId");

                    b.HasOne("mapos_dotnet.Models.Lancamento", "Lancamento")
                        .WithMany("OsLancamentos")
                        .HasForeignKey("LancamentoId");

                    b.HasOne("mapos_dotnet.Models.Usuario", "Usuario")
                        .WithMany("OsList")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("GarantiaTermo");

                    b.Navigation("Lancamento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Produto", b =>
                {
                    b.HasOne("mapos_dotnet.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("mapos_dotnet.Models.ProdutoOs", b =>
                {
                    b.HasOne("mapos_dotnet.Models.Os", "Os")
                        .WithMany("ProdutosOs")
                        .HasForeignKey("OsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mapos_dotnet.Models.Produto", "Produto")
                        .WithMany("ProdutosOs")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Os");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("mapos_dotnet.Models.ServicoOs", b =>
                {
                    b.HasOne("mapos_dotnet.Models.Os", "Os")
                        .WithMany("ServicosOs")
                        .HasForeignKey("OsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mapos_dotnet.Models.Servico", "ServicoNav")
                        .WithMany("ServicosOs")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Os");

                    b.Navigation("ServicoNav");
                });

            modelBuilder.Entity("mapos_dotnet.Models.SessaoCaixa", b =>
                {
                    b.HasOne("mapos_dotnet.Models.Usuario", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Usuario", b =>
                {
                    b.HasOne("mapos_dotnet.Models.Permissao", "Permissao")
                        .WithMany("Usuarios")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Venda", b =>
                {
                    b.HasOne("mapos_dotnet.Models.Cliente", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mapos_dotnet.Models.Lancamento", "Lancamento")
                        .WithMany()
                        .HasForeignKey("LancamentoId");

                    b.HasOne("mapos_dotnet.Models.SessaoCaixa", "SessaoCaixa")
                        .WithMany("Vendas")
                        .HasForeignKey("SessaoCaixaId");

                    b.HasOne("mapos_dotnet.Models.Usuario", "Usuario")
                        .WithMany("Vendas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Cliente");

                    b.Navigation("Lancamento");

                    b.Navigation("SessaoCaixa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Categoria", b =>
                {
                    b.Navigation("Lancamentos");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Cliente", b =>
                {
                    b.Navigation("Cobrancas");

                    b.Navigation("Equipamentos");

                    b.Navigation("Lancamentos");

                    b.Navigation("OsList");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Conta", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Equipamento", b =>
                {
                    b.Navigation("EquipamentosOs");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Garantia", b =>
                {
                    b.Navigation("OsList");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Lancamento", b =>
                {
                    b.Navigation("OsLancamentos");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Marca", b =>
                {
                    b.Navigation("Equipamentos");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Os", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Anotacoes");

                    b.Navigation("Cobrancas");

                    b.Navigation("EquipamentosOs");

                    b.Navigation("ProdutosOs");

                    b.Navigation("ServicosOs");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Permissao", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Produto", b =>
                {
                    b.Navigation("ItensVenda");

                    b.Navigation("ProdutosOs");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Servico", b =>
                {
                    b.Navigation("ServicosOs");
                });

            modelBuilder.Entity("mapos_dotnet.Models.SessaoCaixa", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Usuario", b =>
                {
                    b.Navigation("Lancamentos");

                    b.Navigation("Logs");

                    b.Navigation("OsList");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("mapos_dotnet.Models.Venda", b =>
                {
                    b.Navigation("Cobrancas");

                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
